from __future__ import annotations

PRODUCT_NAME = "照片选片"
PRODUCT_VERSION = "0.9.0-beta.2"
API_VERSION = "1"
SERVICE_PROTOCOL = "PHOTO_AI_SERVICE/1"
WORKER_PROTOCOL = "PHOTO_AI_WORKER/1"
AI_ENGINE_VERSION = "0.9.0-beta.1-py312-cu130"
PYTHON_RUNTIME_VERSION = "3.12.10"
